apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxhello
  name: nginxhello
spec:
  selector:
    matchLabels:
      app: nginxhello
  template:
    metadata:
      labels:
        app: nginxhello
    spec:
      containers:
      - image: nbrown/nginxhello
        name: nginxhello
        resources:
          limits:
            memory: "200Mi"
            cpu: "1"
          requests:
            memory: "100Mi"
            cpu: "0.5"            
        ports:
        - containerPort: 80
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

---

kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: nginxhello
  namespace: default
  labels:
    app: nginxhello  
spec:
  scaleTargetRef:
    kind: Deployment
    name: nginxhello
    apiVersion: extensions/v1beta1
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 25